version: '3.4'
services:
  goerli-geth.avado.dnp.dappnode.eth:
    image: 'goerli-geth.avado.dnp.dappnode.eth:10.4.28'
    build: ./build
    volumes:
      - 'goerli:/goerli'
    ports:
      - '39303:39303'
      - '39303:39303/udp'
      - '8545:8545'
      - '8546:8546'
    restart: always
    environment:
      - 'EXTRA_OPTS=--http.api eth,net,web3,txpool'
volumes:
  goerli: {}
